name: Update JSON from Webhook

on:
  repository_dispatch:
    types: [update_config_json]

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Write webhook payload to JSON
        run: |
          echo '${{ toJson(github.event.client_payload.config) }}' > restaurants-config.json

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add restaurants-config.json
          git diff --cached --quiet || git commit -m "Update config JSON from webhook"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin config-deployment


